<h1><?php echo $pageTitle ?></h1>

<div class="btn-group">
	<a href="<?php echo $this->url($routeName,['action' => 'form']) ?>" class="btn btn-primary">Add</a>
</div>

<br/>
<br/>

<table class="table table-bordered">
	<thead>
		<tr>
			<?php foreach ($tableColumns as $column) : ?>
			<th><?php echo ucfirst($column) ?></th>
			<?php endforeach; ?>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($list as $item) : ?>
		<tr>
			<?php foreach ($tableColumns as $column) : ?>
			<td><?php echo $item->$column ?></td>
			<?php endforeach; ?>
			<td>
				<a href="<?php echo $this->url($routeName,['action' => 'form','id' => $item->id]) ?>">Edit</a>
				<a href="<?php echo $this->url($routeName,['action' => 'delete','id' => $item->id]) ?>">Delete</a>
			</td>
		</tr>
	<?php endforeach; ?>	
	</tbody>
</table>